version: "3.6"
services:
  #nginx:
  #  ports:
  #    - "3000:80"
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=kdia1
      - MONGO_PASSWORD=example
      - SESSION_SECRET=secret
    command: npm run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=kdia1
      - MONGO_INITDB_ROOT_PASSWORD=example
