version: "3.6"
services:
  #nginx:
  #  image: nginx:stable-alpine
  # ports:
  # - "3000:80"
  #volumes:
  # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    build: .
    ports:
      - "3000-3001:3000"
    environment:
      - PORT=3000
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo
    ##restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=kdia1
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis
    #added by me
    restart: always
volumes:
  mongo-db:
